# Data loading

Data loading imports

In [81]:
import numpy as np
import os

### Loading string data

**Parameters:**
- `data_string`: A string containing the data in the format:
  - First line: number of jobs and number of machines (e.g., "10 10")
  - Following lines: for each job, alternating machine numbers and processing times

**Returns:**
- `np.ndarray`: A numpy array of shape `(num_jobs, num_machines, 2)` where the last dimension is `[machine, time]` pairs.

In [82]:
def load_from_string(data_string):
    lines = data_string.strip().split('\n')
    
    num_jobs, num_machines = map(int, lines[0].split())
    
    data = []
    for i in range(1, num_jobs + 1):
        nums = list(map(int, lines[i].split()))
        pairs = [[nums[j], nums[j+1]] for j in range(0, len(nums), 2)]
        data.append(pairs)
    
    return np.array(data)

### Loading from txt file

**Parameters:**
- `key`: The instance key (e.g., 'abz5', 'ft06', 'la01') to load from the dataset.
- `filepath`: Path to the jobshop.txt file. Default is `./data/jobshop.txt`.

**Returns:**
- `np.ndarray`: A numpy array of shape `(num_jobs, num_machines, 2)` where the last dimension is `[machine, time]` pairs.

In [83]:
def load_from_dataset(key, filepath=os.path.join('.', 'data', 'jobshop.txt')):    
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Dataset file not found at {filepath}")
    
    with open(filepath, 'r') as f:
        lines = f.readlines()
    
    instance_marker = f'instance {key}'
    start_idx = None
    
    for i, line in enumerate(lines):
        if instance_marker in line:
            start_idx = i
            break
    
    if start_idx is None:
        raise ValueError(f"Instance '{key}' not found in the dataset")
    
    dimensions_line = None
    data_start_idx = None
    
    for i in range(start_idx, min(start_idx + 10, len(lines))):
        line = lines[i].strip()
        if line and line[0].isdigit():
            parts = line.split()
            if len(parts) >= 2 and all(p.isdigit() for p in parts[:2]):
                dimensions_line = line
                data_start_idx = i + 1
                break
    
    if dimensions_line is None:
        raise ValueError(f"Could not parse dimensions for instance '{key}'")
    
    num_jobs, num_machines = map(int, dimensions_line.split()[:2])
    
    data = []
    for i in range(data_start_idx, data_start_idx + num_jobs):
        if i < len(lines):
            line = lines[i].strip()
            if line and not line.startswith('+'):
                nums = list(map(int, line.split()))
                pairs = [[nums[j], nums[j+1]] for j in range(0, len(nums), 2)]
                data.append(pairs)
    
    if len(data) != num_jobs:
        raise ValueError(f"Expected {num_jobs} jobs, but found {len(data)}")
    
    return np.array(data)

## Example Usage

In [84]:
sample_data_string = """10 10
 4 88 8 68 6 94 5 99 1 67 2 89 9 77 7 99 0 86 3 92
 5 72 3 50 6 69 4 75 2 94 8 66 0 92 1 82 7 94 9 63
 9 83 8 61 0 83 1 65 6 64 5 85 7 78 4 85 2 55 3 77
 7 94 2 68 1 61 4 99 3 54 6 75 5 66 0 76 9 63 8 67
 3 69 4 88 9 82 8 95 0 99 2 67 6 95 5 68 7 67 1 86
 1 99 4 81 5 64 6 66 8 80 2 80 7 69 9 62 3 79 0 88
 7 50 1 86 4 97 3 96 0 95 8 97 2 66 5 99 6 52 9 71
 4 98 6 73 3 82 2 51 1 71 5 94 7 85 0 62 8 95 9 79
 0 94 6 71 3 81 7 85 1 66 2 90 4 76 5 58 8 93 9 97
 3 50 0 59 1 82 8 67 7 56 9 96 6 58 4 81 5 59 2 96"""

result_from_string = load_from_string(sample_data_string)
print("Data from string:")
print(f"Shape: {result_from_string.shape}")
print(result_from_string)

Data from string:
Shape: (10, 10, 2)
[[[ 4 88]
  [ 8 68]
  [ 6 94]
  [ 5 99]
  [ 1 67]
  [ 2 89]
  [ 9 77]
  [ 7 99]
  [ 0 86]
  [ 3 92]]

 [[ 5 72]
  [ 3 50]
  [ 6 69]
  [ 4 75]
  [ 2 94]
  [ 8 66]
  [ 0 92]
  [ 1 82]
  [ 7 94]
  [ 9 63]]

 [[ 9 83]
  [ 8 61]
  [ 0 83]
  [ 1 65]
  [ 6 64]
  [ 5 85]
  [ 7 78]
  [ 4 85]
  [ 2 55]
  [ 3 77]]

 [[ 7 94]
  [ 2 68]
  [ 1 61]
  [ 4 99]
  [ 3 54]
  [ 6 75]
  [ 5 66]
  [ 0 76]
  [ 9 63]
  [ 8 67]]

 [[ 3 69]
  [ 4 88]
  [ 9 82]
  [ 8 95]
  [ 0 99]
  [ 2 67]
  [ 6 95]
  [ 5 68]
  [ 7 67]
  [ 1 86]]

 [[ 1 99]
  [ 4 81]
  [ 5 64]
  [ 6 66]
  [ 8 80]
  [ 2 80]
  [ 7 69]
  [ 9 62]
  [ 3 79]
  [ 0 88]]

 [[ 7 50]
  [ 1 86]
  [ 4 97]
  [ 3 96]
  [ 0 95]
  [ 8 97]
  [ 2 66]
  [ 5 99]
  [ 6 52]
  [ 9 71]]

 [[ 4 98]
  [ 6 73]
  [ 3 82]
  [ 2 51]
  [ 1 71]
  [ 5 94]
  [ 7 85]
  [ 0 62]
  [ 8 95]
  [ 9 79]]

 [[ 0 94]
  [ 6 71]
  [ 3 81]
  [ 7 85]
  [ 1 66]
  [ 2 90]
  [ 4 76]
  [ 5 58]
  [ 8 93]
  [ 9 97]]

 [[ 3 50]
  [ 0 59]
  [ 1 82]
  [ 8 67]
  [ 7

In [85]:
result_from_dataset = load_from_dataset('abz5')
print("\nData from dataset (abz5):")
print(f"Shape: {result_from_dataset.shape}")
print(result_from_dataset)


Data from dataset (abz5):
Shape: (10, 10, 2)
[[[ 4 88]
  [ 8 68]
  [ 6 94]
  [ 5 99]
  [ 1 67]
  [ 2 89]
  [ 9 77]
  [ 7 99]
  [ 0 86]
  [ 3 92]]

 [[ 5 72]
  [ 3 50]
  [ 6 69]
  [ 4 75]
  [ 2 94]
  [ 8 66]
  [ 0 92]
  [ 1 82]
  [ 7 94]
  [ 9 63]]

 [[ 9 83]
  [ 8 61]
  [ 0 83]
  [ 1 65]
  [ 6 64]
  [ 5 85]
  [ 7 78]
  [ 4 85]
  [ 2 55]
  [ 3 77]]

 [[ 7 94]
  [ 2 68]
  [ 1 61]
  [ 4 99]
  [ 3 54]
  [ 6 75]
  [ 5 66]
  [ 0 76]
  [ 9 63]
  [ 8 67]]

 [[ 3 69]
  [ 4 88]
  [ 9 82]
  [ 8 95]
  [ 0 99]
  [ 2 67]
  [ 6 95]
  [ 5 68]
  [ 7 67]
  [ 1 86]]

 [[ 1 99]
  [ 4 81]
  [ 5 64]
  [ 6 66]
  [ 8 80]
  [ 2 80]
  [ 7 69]
  [ 9 62]
  [ 3 79]
  [ 0 88]]

 [[ 7 50]
  [ 1 86]
  [ 4 97]
  [ 3 96]
  [ 0 95]
  [ 8 97]
  [ 2 66]
  [ 5 99]
  [ 6 52]
  [ 9 71]]

 [[ 4 98]
  [ 6 73]
  [ 3 82]
  [ 2 51]
  [ 1 71]
  [ 5 94]
  [ 7 85]
  [ 0 62]
  [ 8 95]
  [ 9 79]]

 [[ 0 94]
  [ 6 71]
  [ 3 81]
  [ 7 85]
  [ 1 66]
  [ 2 90]
  [ 4 76]
  [ 5 58]
  [ 8 93]
  [ 9 97]]

 [[ 3 50]
  [ 0 59]
  [ 1 82]
  [ 8 

In [ ]:
print("\nAre the results identical?", np.array_equal(result_from_string, result_from_dataset))

assert load_from_dataset('yn2').shape == (20, 20, 2), f"yn2 should have 20 jobs and 20 machines, but got {load_from_dataset('yn2').shape}"
assert load_from_dataset('yn1').shape == (20, 20, 2), f"yn1 should have 20 jobs and 20 machines, but got {load_from_dataset('yn1').shape}"
assert load_from_dataset('swv20').shape == (50, 10, 2), f"swv20 should have 50 jobs and 10 machines, but got {load_from_dataset('swv20').shape}"


Are the results identical? True


AssertionError: yn2 should have 20 jobs and 20 machines, but got (20, 20, 2)