# Data loading

Data loading imports

In [66]:
import numpy as np
import os

### Loading string data

**Parameters:**
- `data_string`: A string containing the data in the format:
  - First line: number of jobs and number of machines (e.g., "10 10")
  - Following lines: for each job, alternating machine numbers and processing times

**Returns:**
- `np.ndarray`: A numpy array containing the parsed data. Each row represents a job with alternating machine numbers and processing times.

In [67]:
def load_from_string(data_string):
    lines = data_string.strip().split('\n')
    
    # Parse the first line to get dimensions
    dimensions = list(map(int, lines[0].split()))
    num_jobs = dimensions[0]
    
    # Parse the data rows
    data = []
    for i in range(1, num_jobs + 1):
        row = list(map(int, lines[i].split()))
        data.append(row)
    
    return np.array(data)

### Loading from txt file

**Parameters:**
- `key`: The instance key (e.g., 'abz5', 'ft06', 'la01') to load from the dataset.
- `data_dir`: Path to the directory containing the jobshop.txt file. Default is './data'.

**Returns:**
- `np.ndarray`: A numpy array containing the parsed data for the specified instance.

In [68]:
def load_from_dataset(key, filepath=os.path.join('.', 'data', 'jobshop.txt')):    
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Dataset file not found at {filepath}")
    
    with open(filepath, 'r') as f:
        lines = f.readlines()
    
    instance_marker = f'instance {key}'
    start_idx = None
    
    for i, line in enumerate(lines):
        if instance_marker in line:
            start_idx = i
            break
    
    if start_idx is None:
        raise ValueError(f"Instance '{key}' not found in the dataset")
    
    dimensions_line = None
    data_start_idx = None
    
    for i in range(start_idx, min(start_idx + 10, len(lines))):
        line = lines[i].strip()
        if line and line[0].isdigit():
            parts = line.split()
            if len(parts) >= 2 and all(p.isdigit() for p in parts[:2]):
                dimensions_line = line
                data_start_idx = i + 1
                break
    
    if dimensions_line is None:
        raise ValueError(f"Could not parse dimensions for instance '{key}'")
    
    num_jobs, num_machines = map(int, dimensions_line.split()[:2])
    
    data = []
    for i in range(data_start_idx, data_start_idx + num_jobs):
        if i < len(lines):
            line = lines[i].strip()
            if line and not line.startswith('+'):
                row = list(map(int, line.split()))
                data.append(row)
    
    if len(data) != num_jobs:
        raise ValueError(f"Expected {num_jobs} jobs, but found {len(data)}")
    
    return np.array(data)

## Example Usage

In [69]:
sample_data_string = """10 10
 4 88 8 68 6 94 5 99 1 67 2 89 9 77 7 99 0 86 3 92
 5 72 3 50 6 69 4 75 2 94 8 66 0 92 1 82 7 94 9 63
 9 83 8 61 0 83 1 65 6 64 5 85 7 78 4 85 2 55 3 77
 7 94 2 68 1 61 4 99 3 54 6 75 5 66 0 76 9 63 8 67
 3 69 4 88 9 82 8 95 0 99 2 67 6 95 5 68 7 67 1 86
 1 99 4 81 5 64 6 66 8 80 2 80 7 69 9 62 3 79 0 88
 7 50 1 86 4 97 3 96 0 95 8 97 2 66 5 99 6 52 9 71
 4 98 6 73 3 82 2 51 1 71 5 94 7 85 0 62 8 95 9 79
 0 94 6 71 3 81 7 85 1 66 2 90 4 76 5 58 8 93 9 97
 3 50 0 59 1 82 8 67 7 56 9 96 6 58 4 81 5 59 2 96"""

result_from_string = load_from_string(sample_data_string)
print("Data from string:")
print(f"Shape: {result_from_string.shape}")
print(result_from_string)

Data from string:
Shape: (10, 20)
[[ 4 88  8 68  6 94  5 99  1 67  2 89  9 77  7 99  0 86  3 92]
 [ 5 72  3 50  6 69  4 75  2 94  8 66  0 92  1 82  7 94  9 63]
 [ 9 83  8 61  0 83  1 65  6 64  5 85  7 78  4 85  2 55  3 77]
 [ 7 94  2 68  1 61  4 99  3 54  6 75  5 66  0 76  9 63  8 67]
 [ 3 69  4 88  9 82  8 95  0 99  2 67  6 95  5 68  7 67  1 86]
 [ 1 99  4 81  5 64  6 66  8 80  2 80  7 69  9 62  3 79  0 88]
 [ 7 50  1 86  4 97  3 96  0 95  8 97  2 66  5 99  6 52  9 71]
 [ 4 98  6 73  3 82  2 51  1 71  5 94  7 85  0 62  8 95  9 79]
 [ 0 94  6 71  3 81  7 85  1 66  2 90  4 76  5 58  8 93  9 97]
 [ 3 50  0 59  1 82  8 67  7 56  9 96  6 58  4 81  5 59  2 96]]


In [70]:
result_from_dataset = load_from_dataset('abz5')
print("\nData from dataset (abz5):")
print(f"Shape: {result_from_dataset.shape}")
print(result_from_dataset)


Data from dataset (abz5):
Shape: (10, 20)
[[ 4 88  8 68  6 94  5 99  1 67  2 89  9 77  7 99  0 86  3 92]
 [ 5 72  3 50  6 69  4 75  2 94  8 66  0 92  1 82  7 94  9 63]
 [ 9 83  8 61  0 83  1 65  6 64  5 85  7 78  4 85  2 55  3 77]
 [ 7 94  2 68  1 61  4 99  3 54  6 75  5 66  0 76  9 63  8 67]
 [ 3 69  4 88  9 82  8 95  0 99  2 67  6 95  5 68  7 67  1 86]
 [ 1 99  4 81  5 64  6 66  8 80  2 80  7 69  9 62  3 79  0 88]
 [ 7 50  1 86  4 97  3 96  0 95  8 97  2 66  5 99  6 52  9 71]
 [ 4 98  6 73  3 82  2 51  1 71  5 94  7 85  0 62  8 95  9 79]
 [ 0 94  6 71  3 81  7 85  1 66  2 90  4 76  5 58  8 93  9 97]
 [ 3 50  0 59  1 82  8 67  7 56  9 96  6 58  4 81  5 59  2 96]]


In [71]:
print("\nAre the results identical?", np.array_equal(result_from_string, result_from_dataset))


Are the results identical? True
