# Data loading

Data loading imports

In [11]:
import numpy as np
import os

### Loading string data

**Parameters:**
- `data_string`: A string containing the data in the format:
  - First line: number of jobs and number of machines (e.g., "10 10")
  - Following lines: for each job, alternating machine numbers and processing times

**Returns:**
- `np.ndarray`: A numpy array of shape `(num_jobs, num_machines, 2)` where the last dimension is `[machine, time]` pairs.

In [12]:
def load_from_string(data_string):
    lines = data_string.strip().split('\n')
    
    num_jobs, num_machines = map(int, lines[0].split())
    
    data = []
    for i in range(1, num_jobs + 1):
        nums = list(map(int, lines[i].split()))
        pairs = [[nums[j], nums[j+1]] for j in range(0, len(nums), 2)]
        data.append(pairs)
    
    return np.array(data)

### Loading from txt file

**Parameters:**
- `key`: The instance key (e.g., 'abz5', 'ft06', 'la01') to load from the dataset.
- `filepath`: Path to the jobshop.txt file. Default is `./data/jobshop.txt`.

**Returns:**
- `np.ndarray`: A numpy array of shape `(num_jobs, num_machines, 2)` where the last dimension is `[machine, time]` pairs.

In [13]:
def load_from_dataset(key, filepath=os.path.join('.', 'data', 'jobshop.txt')):    
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Dataset file not found at {filepath}")
    
    with open(filepath, 'r') as f:
        lines = f.readlines()
    
    instance_marker = f'instance {key}'
    start_idx = None
    
    for i, line in enumerate(lines):
        if instance_marker in line:
            start_idx = i
            break
    
    if start_idx is None:
        raise ValueError(f"Instance '{key}' not found in the dataset")
    
    dimensions_line = None
    data_start_idx = None
    
    for i in range(start_idx, min(start_idx + 10, len(lines))):
        line = lines[i].strip()
        if line and line[0].isdigit():
            parts = line.split()
            if len(parts) >= 2 and all(p.isdigit() for p in parts[:2]):
                dimensions_line = line
                data_start_idx = i + 1
                break
    
    if dimensions_line is None:
        raise ValueError(f"Could not parse dimensions for instance '{key}'")
    
    num_jobs, num_machines = map(int, dimensions_line.split()[:2])
    
    data = []
    for i in range(data_start_idx, data_start_idx + num_jobs):
        if i < len(lines):
            line = lines[i].strip()
            if line and not line.startswith('+'):
                nums = list(map(int, line.split()))
                pairs = [[nums[j], nums[j+1]] for j in range(0, len(nums), 2)]
                data.append(pairs)
    
    if len(data) != num_jobs:
        raise ValueError(f"Expected {num_jobs} jobs, but found {len(data)}")
    
    return np.array(data), num_jobs, num_machines

## Example Usage

In [14]:
sample_data_string = """10 10
 4 88 8 68 6 94 5 99 1 67 2 89 9 77 7 99 0 86 3 92
 5 72 3 50 6 69 4 75 2 94 8 66 0 92 1 82 7 94 9 63
 9 83 8 61 0 83 1 65 6 64 5 85 7 78 4 85 2 55 3 77
 7 94 2 68 1 61 4 99 3 54 6 75 5 66 0 76 9 63 8 67
 3 69 4 88 9 82 8 95 0 99 2 67 6 95 5 68 7 67 1 86
 1 99 4 81 5 64 6 66 8 80 2 80 7 69 9 62 3 79 0 88
 7 50 1 86 4 97 3 96 0 95 8 97 2 66 5 99 6 52 9 71
 4 98 6 73 3 82 2 51 1 71 5 94 7 85 0 62 8 95 9 79
 0 94 6 71 3 81 7 85 1 66 2 90 4 76 5 58 8 93 9 97
 3 50 0 59 1 82 8 67 7 56 9 96 6 58 4 81 5 59 2 96"""

result_from_string = load_from_string(sample_data_string)
print("Data from string:")
print(f"Shape: {result_from_string.shape}")
print(result_from_string)

Data from string:
Shape: (10, 10, 2)
[[[ 4 88]
  [ 8 68]
  [ 6 94]
  [ 5 99]
  [ 1 67]
  [ 2 89]
  [ 9 77]
  [ 7 99]
  [ 0 86]
  [ 3 92]]

 [[ 5 72]
  [ 3 50]
  [ 6 69]
  [ 4 75]
  [ 2 94]
  [ 8 66]
  [ 0 92]
  [ 1 82]
  [ 7 94]
  [ 9 63]]

 [[ 9 83]
  [ 8 61]
  [ 0 83]
  [ 1 65]
  [ 6 64]
  [ 5 85]
  [ 7 78]
  [ 4 85]
  [ 2 55]
  [ 3 77]]

 [[ 7 94]
  [ 2 68]
  [ 1 61]
  [ 4 99]
  [ 3 54]
  [ 6 75]
  [ 5 66]
  [ 0 76]
  [ 9 63]
  [ 8 67]]

 [[ 3 69]
  [ 4 88]
  [ 9 82]
  [ 8 95]
  [ 0 99]
  [ 2 67]
  [ 6 95]
  [ 5 68]
  [ 7 67]
  [ 1 86]]

 [[ 1 99]
  [ 4 81]
  [ 5 64]
  [ 6 66]
  [ 8 80]
  [ 2 80]
  [ 7 69]
  [ 9 62]
  [ 3 79]
  [ 0 88]]

 [[ 7 50]
  [ 1 86]
  [ 4 97]
  [ 3 96]
  [ 0 95]
  [ 8 97]
  [ 2 66]
  [ 5 99]
  [ 6 52]
  [ 9 71]]

 [[ 4 98]
  [ 6 73]
  [ 3 82]
  [ 2 51]
  [ 1 71]
  [ 5 94]
  [ 7 85]
  [ 0 62]
  [ 8 95]
  [ 9 79]]

 [[ 0 94]
  [ 6 71]
  [ 3 81]
  [ 7 85]
  [ 1 66]
  [ 2 90]
  [ 4 76]
  [ 5 58]
  [ 8 93]
  [ 9 97]]

 [[ 3 50]
  [ 0 59]
  [ 1 82]
  [ 8 67]
  [ 7

In [15]:
result_from_dataset, num_jobs, num_machines = load_from_dataset('abz5')
print("\nData from dataset (abz5):")
print(f"Shape: {result_from_dataset.shape}")
print(result_from_dataset)


Data from dataset (abz5):
Shape: (10, 10, 2)
[[[ 4 88]
  [ 8 68]
  [ 6 94]
  [ 5 99]
  [ 1 67]
  [ 2 89]
  [ 9 77]
  [ 7 99]
  [ 0 86]
  [ 3 92]]

 [[ 5 72]
  [ 3 50]
  [ 6 69]
  [ 4 75]
  [ 2 94]
  [ 8 66]
  [ 0 92]
  [ 1 82]
  [ 7 94]
  [ 9 63]]

 [[ 9 83]
  [ 8 61]
  [ 0 83]
  [ 1 65]
  [ 6 64]
  [ 5 85]
  [ 7 78]
  [ 4 85]
  [ 2 55]
  [ 3 77]]

 [[ 7 94]
  [ 2 68]
  [ 1 61]
  [ 4 99]
  [ 3 54]
  [ 6 75]
  [ 5 66]
  [ 0 76]
  [ 9 63]
  [ 8 67]]

 [[ 3 69]
  [ 4 88]
  [ 9 82]
  [ 8 95]
  [ 0 99]
  [ 2 67]
  [ 6 95]
  [ 5 68]
  [ 7 67]
  [ 1 86]]

 [[ 1 99]
  [ 4 81]
  [ 5 64]
  [ 6 66]
  [ 8 80]
  [ 2 80]
  [ 7 69]
  [ 9 62]
  [ 3 79]
  [ 0 88]]

 [[ 7 50]
  [ 1 86]
  [ 4 97]
  [ 3 96]
  [ 0 95]
  [ 8 97]
  [ 2 66]
  [ 5 99]
  [ 6 52]
  [ 9 71]]

 [[ 4 98]
  [ 6 73]
  [ 3 82]
  [ 2 51]
  [ 1 71]
  [ 5 94]
  [ 7 85]
  [ 0 62]
  [ 8 95]
  [ 9 79]]

 [[ 0 94]
  [ 6 71]
  [ 3 81]
  [ 7 85]
  [ 1 66]
  [ 2 90]
  [ 4 76]
  [ 5 58]
  [ 8 93]
  [ 9 97]]

 [[ 3 50]
  [ 0 59]
  [ 1 82]
  [ 8 

In [17]:
print("\nAre the results identical?", np.array_equal(result_from_string, result_from_dataset))

assert load_from_dataset('yn2').shape == (20, 20, 2), f"yn2 should have 20 jobs and 20 machines, but got {load_from_dataset('yn2').shape}"
assert load_from_dataset('yn1').shape == (20, 20, 2), f"yn1 should have 20 jobs and 20 machines, but got {load_from_dataset('yn1').shape}"
assert load_from_dataset('swv20').shape == (50, 10, 2), f"swv20 should have 50 jobs and 10 machines, but got {load_from_dataset('swv20').shape}"


Are the results identical? True


AttributeError: 'tuple' object has no attribute 'shape'

## Generating an initial random solution

As we know the number of jobs and of machines, we can proceed to create an initial random solution.

In [18]:
def generate_random_solution(num_jobs, num_machines):
    # This function generates a random candidate solution for the job shop scheduling problem.
    steps_job = np.zeros(num_jobs, dtype=int)
    candidate_solution = np.zeros(num_jobs * num_machines, dtype=int) # This array will hold the sequence of job assignments for the candidate solution.
    counter = 0
    while (steps_job != np.repeat(num_jobs, num_jobs)).any(): # This loop continues until all jobs have been assigned to all machines.
        random_job = np.random.randint(num_jobs)
        while steps_job[random_job] == num_jobs:
            random_job = np.random.randint(num_jobs)
        candidate_solution[counter] = random_job # Assign the random job to the current position in the candidate solution.
        counter += 1
        steps_job[random_job] += 1
    return candidate_solution   # Return the generated random candidate solution.

## Calculate the makespan for a candidate solution

With this function we calculate how much time is spent by a candidate solution to schedule all the assigned tasks.

In [19]:
def calculate_time(candidate_solution):
    steps_job = np.zeros(num_jobs, dtype=int)
    steps_machines = np.zeros(num_machines, dtype=int)
    machines = np.array(np.repeat([np.repeat(np.zeros(shape=(1, 4)), num_jobs, axis=0)], num_machines, axis=0), dtype=int)
    time = 0
    for job in candidate_solution:
        machine, processing_time = result_from_dataset[job, steps_job[job]]
        machine_used_for_job, _ = result_from_dataset[job, steps_job[job] - 1]
        if machines[machine_used_for_job][steps_machines[machine_used_for_job] - 1][3] > time:
            # if a machine has been employed already for the same job and is not available at the current time
            # the time is updated to the time when the machine will be available
            time = machines[machine_used_for_job][steps_machines[machine_used_for_job] - 1][3]
        if machines[machine][steps_machines[machine] - 1][3] > time:
            # if a machine is used already for another job and is not available at the current time
            # the time is updated to the time when the machine will be available
            time = machines[machine][steps_machines[machine] - 1][3]
        machines[machine][steps_machines[machine]] = [job, steps_job[job], time, time + processing_time]
        steps_job[job] += 1
        steps_machines[machine] += 1
    return time

## Tweak a candidate solution

With this function the position of two random indexes of the candidate solution are swapped, in order to obtain a new candidate solution.

In [20]:
def tweak_candidate_solution(candidate_solution):
    index_one, index_two = np.random.randint(len(candidate_solution)), np.random.randint(len(candidate_solution))
    while index_one == index_two:
        index_two = np.random.randint(len(candidate_solution))
    candidate_solution[index_one], candidate_solution[index_two] = candidate_solution[index_two], candidate_solution[index_one] 
    return candidate_solution

# Simulated Annealing
## Why this function has been chosen as the trajectory based function
It is flexible, and allows us to get from high exploration at the beginning to high exploitation at the end.

In [21]:
def simulated_annealing(input_solution, t = 120, target_time = 60):
    candidate_solution = input_solution.copy()
    best_solution = candidate_solution.copy() # the best solution is initialized as the input solution
    # we iterate as long as the temperature is greater than 0 and we have not obtained a solution with the specified target time
    while t > 0 and calculate_time(best_solution) > target_time: 
        tweaked_solution = tweak_candidate_solution(candidate_solution.copy())
        quality_temp_ratio = -(calculate_time(tweaked_solution) - calculate_time(candidate_solution)) / t
        # we apply the same conditions as in the metropolis algorithm
        # if the tweaked solution is better than the candidate solution or a random number is less than the exponential of the quality-temperature ratio
        # we update the candidate solution accordingly
        if calculate_time(tweaked_solution) < calculate_time(candidate_solution):
            candidate_solution = tweaked_solution
        elif np.random.rand() < np.exp(quality_temp_ratio):
            candidate_solution = tweaked_solution
        t -= 1 # we decrease the temperature at each iteration
        if calculate_time(candidate_solution) < calculate_time(best_solution):
            # if the candidate solution is better than the best solution, we update the best solution
            best_solution = candidate_solution.copy()
    return best_solution



## Testing the functions for dataset abz5

In [23]:
candidate_solution = generate_random_solution(num_jobs, num_machines)
print(candidate_solution, calculate_time(candidate_solution))
best_solution = simulated_annealing(candidate_solution)
print(best_solution, calculate_time(best_solution))

[1 0 8 2 2 7 9 3 1 4 8 0 0 5 5 2 1 3 3 4 4 9 6 7 8 7 4 6 9 4 3 8 8 6 9 1 6
 7 4 3 7 8 2 2 2 9 6 8 4 6 5 7 9 7 6 5 8 6 7 4 6 6 2 5 3 3 5 0 0 5 8 3 8 1
 3 5 0 2 5 3 7 2 9 0 4 1 4 0 7 0 0 9 1 1 9 9 5 1 2 1] 3419
[1 7 6 4 2 0 9 3 1 2 8 7 0 5 4 5 1 1 8 5 7 6 4 9 5 3 4 6 9 7 3 8 2 5 9 7 4
 9 0 3 9 8 4 2 2 9 3 8 0 3 6 0 4 6 4 8 8 5 7 1 6 6 3 3 7 2 0 6 1 1 8 3 8 6
 6 7 0 5 9 2 4 2 3 0 7 1 4 0 7 0 2 9 1 5 9 5 5 1 2 8] 2812
